/* Generated by tools/generate_types.py from evidence/census/dwarf-dies.jsonl. */
#ifndef ICYTOWER_RECOVERED_TYPES_H
#define ICYTOWER_RECOVERED_TYPES_H
#include <stddef.h>

typedef struct Tplayer {
    double x;
    double y;
    double sx;
    double sy;
    double max_s;
    int level;
    int score;
    int best_combo;
    int status;
    int jump_key;
    int frame;
    int in_combo;
    int acc_level;
    int acc_jumps;
    int dead;
    int rotate;
    int angle;
    int edge;
    int edge_drawn;
    int bounce;
    int shake;
    int latest_combo;
    int show_combo;
    int no_combo_top_floor;
    int biggest_lost_combo;
    int ccc[5];
    int jcTop[5];
    int jc[5];
} Tplayer;

#define RECOVERED_STATIC_ASSERT(expr, name) typedef char recovered_static_assert_##name[(expr) ? 1 : -1]
RECOVERED_STATIC_ASSERT(sizeof(Tplayer) == 184, tplayer_size);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, x) == 0, tplayer_x);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, y) == 8, tplayer_y);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, sx) == 16, tplayer_sx);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, sy) == 24, tplayer_sy);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, max_s) == 32, tplayer_max_s);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, level) == 40, tplayer_level);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, score) == 44, tplayer_score);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, best_combo) == 48, tplayer_best_combo);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, status) == 52, tplayer_status);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, jump_key) == 56, tplayer_jump_key);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, frame) == 60, tplayer_frame);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, in_combo) == 64, tplayer_in_combo);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, acc_level) == 68, tplayer_acc_level);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, acc_jumps) == 72, tplayer_acc_jumps);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, dead) == 76, tplayer_dead);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, rotate) == 80, tplayer_rotate);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, angle) == 84, tplayer_angle);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, edge) == 88, tplayer_edge);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, edge_drawn) == 92, tplayer_edge_drawn);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, bounce) == 96, tplayer_bounce);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, shake) == 100, tplayer_shake);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, latest_combo) == 104, tplayer_latest_combo);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, show_combo) == 108, tplayer_show_combo);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, no_combo_top_floor) == 112, tplayer_no_combo_top_floor);
RECOVERED_STATIC_ASSERT(offsetof(Tplayer, biggest_lost_combo) == 116, tplayer_biggest_lost_combo);

#endif
