"""Generate audited shared C layouts from the local DWARF census."""
import argparse
import json

from common import ROOT

PLAYER_MEMBERS = [
    ('double', 'x', 0), ('double', 'y', 8), ('double', 'sx', 16), ('double', 'sy', 24),
    ('double', 'max_s', 32), ('int', 'level', 40), ('int', 'score', 44),
    ('int', 'best_combo', 48), ('int', 'status', 52), ('int', 'jump_key', 56),
    ('int', 'frame', 60), ('int', 'in_combo', 64), ('int', 'acc_level', 68),
    ('int', 'acc_jumps', 72), ('int', 'dead', 76), ('int', 'rotate', 80),
    ('int', 'angle', 84), ('int', 'edge', 88), ('int', 'edge_drawn', 92),
    ('int', 'bounce', 96), ('int', 'shake', 100), ('int', 'latest_combo', 104),
    ('int', 'show_combo', 108), ('int', 'no_combo_top_floor', 112),
    ('int', 'biggest_lost_combo', 116), ('int', 'ccc[5]', 120),
    ('int', 'jcTop[5]', 140), ('int', 'jc[5]', 160),
]


def census_members():
    rows = [json.loads(line) for line in (ROOT / 'evidence/census/dwarf-dies.jsonl').read_text(encoding='utf-8').splitlines()]
    typedef = next(row for row in rows if row['tag'] == 'DW_TAG_typedef' and row.get('name') == 'Tplayer'
                   and row.get('decl_file_path', '').endswith('/player.h'))
    members = [row for row in rows if row.get('parent') == typedef['type_ref'] and row['tag'] == 'DW_TAG_member']
    return [(row['name'], int(row['resolved']['DW_AT_data_member_location'].split('DW_OP_plus_uconst: ')[1].split(')')[0]))
            for row in members]


def render():
    observed = census_members()
    expected = [(name.split('[')[0], offset) for _, name, offset in PLAYER_MEMBERS]
    if observed != expected:
        raise ValueError('Tplayer DWARF member layout differs from generator specification')
    lines = [
        '/* Generated by tools/generate_types.py from evidence/census/dwarf-dies.jsonl. */',
        '#ifndef ICYTOWER_RECOVERED_TYPES_H', '#define ICYTOWER_RECOVERED_TYPES_H', '#include <stddef.h>', '',
        'typedef struct Tplayer {'
    ]
    for c_type, name, _ in PLAYER_MEMBERS:
        lines.append('    %s %s;' % (c_type, name))
    lines += ['} Tplayer;', '', '#define RECOVERED_STATIC_ASSERT(expr, name) typedef char recovered_static_assert_##name[(expr) ? 1 : -1]',
              'RECOVERED_STATIC_ASSERT(sizeof(Tplayer) == 184, tplayer_size);']
    for _, name, offset in PLAYER_MEMBERS:
        if '[' not in name:
            lines.append('RECOVERED_STATIC_ASSERT(offsetof(Tplayer, %s) == %d, tplayer_%s);' % (name, offset, name))
    lines += ['', '#endif', '']
    return '\n'.join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    path = ROOT / 'include/recovered_types.h'
    content = render()
    if a.check:
        if not path.exists() or path.read_text(encoding='utf-8') != content:
            raise ValueError('Generated type header is stale: include/recovered_types.h')
        print('PASS: recovered shared types agree with DWARF census.')
    else:
        path.write_bytes(content.encode('utf-8'))
        print(path.relative_to(ROOT))


if __name__ == '__main__':
    main()
